server:
  port: 8080

spring:
  application:
    name: course
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    

  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/dkmicroservices?allowPublicKeyRetrieval=true&sslMode=DISABLED&createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo
    username: root
    password: 2522